services:
  pf-frontend:
    image: pf-frontend
    stdin_open: true
    ports:
      - 3000:3000
    networks:
      - pf-net
    environment:
      - NGINX_PORT=3000
      - NGINX_PROXY=http://localhost:5001/api
  pf-backend:
    image: pf-backend
    ports:
      - 5001:5001
    depends_on:
      - database
    networks:
      - pf-net
    environment:
      - MONGO_URI=mongodb://database:27017/shorterURL
      - JWT_SECRET=888THAILANDSMILEY

  database:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - pf-net
    volumes:
      - mongo-data:/data/db

networks:
  pf-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local
